version: '2'

services:
  mariadb:
    image: mariadb:10.3
    container_name: maziadb
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "1"
    #ports:
    #  - "3306:3306"
    networks:
      docker-lamp:
        ipv4_address: 10.5.0.6
networks:
  docker-lamp:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
